---
title: "DS301 hw6"
author: "Henry Underhill"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
head(Boston)
```

```{r}
#problem 1a
m_crime = median(Boston$crim)
m_crime
```

```{r}
#problem 1bi
n = dim(Boston)[1]

set.seed(12)
B = 1000
bootstrap_median = rep(0,B)
for(i in 1:B){
  index = sample(1:n,n,replace=TRUE)
  bootsample = Boston[index,]
  bootstrap_median[i] = median(bootsample$crim)
}
```

```{r}
#problem 1bii
sqrt(sum((bootstrap_median-mean(bootstrap_median))^2)/(B-1))
```

```{r}
#problem 1c
Y = rep(0,n)
Y[Boston$crim> m_crime] = 1
Boston$Y = Y
```

```{r}
#problem 1d
logit = glm(Y~nox + age, data = Boston)
summary(logit)
```

```{r}
#problem 1f
logit2 = glm(Y~nox + age + rad, data = Boston)
summary(logit2)

set.seed(12)
LOOCV_error2 = rep(0,n)

for(i in 1:n){
  LOOCV_sample2 = Boston[-c(i), ]
  model2 = glm(Y~nox + age +rad, data = LOOCV_sample2)
  LOOCV_error2[i] = sum((model2$residuals/(1-lm.influence(model2)$hat))^2)
}

test_error2 = sum(LOOCV_error2) / n
test_error2
```

```{r}
#problem 1f

set.seed(12)
LOOCV_error = rep(0,n)

for(i in 1:n){
  LOOCV_sample = Boston[-c(i), ]
  model = glm(Y~nox + age, data = LOOCV_sample)
  LOOCV_error[i] = sum((model$residuals/(1-lm.influence(model)$hat))^2)
}

test_error = sum(LOOCV_error) / n
test_error
```


```{r}
#problem 2a
Boston$Y = NULL

library(leaps)

regfit = regsubsets(crim~.,data=Boston,nbest=1,nvmax=13)
regfit.sum = summary(regfit)
regfit.sum

p = rowSums(regfit.sum$which)
adjr2 = regfit.sum$adjr2
cp = regfit.sum$cp
rss = regfit.sum$rss
AIC = n*log(rss/n) + 2*(p-1)
BIC = n*log(rss/n) + (p-1)*log(n)

cbind(p,rss,adjr2,cp,AIC,BIC)
plot(p,BIC)
plot(p,AIC)

which.min(BIC)
which.min(AIC)
which.min(cp)
which.max(adjr2)

model1 = coef(regfit,8)
model2 = coef(regfit,9)
model3 = coef(regfit,10)
```

```{r}
#problem 2c
regfit.bwd = regsubsets(crim~.,data=Boston,nvmax=13, method="backward")
regfit.bwd.sum = summary(regfit.bwd)

regfit.bwd.sum

p = rowSums(regfit.bwd.sum$which)
adjr2 = regfit.bwd.sum$adjr2
cp = regfit.bwd.sum$cp
rss = regfit.bwd.sum$rss
BIC = n*log(rss/n) + (p-1)*log(n)

cbind(p,rss,adjr2,cp,AIC,BIC)
plot(p,BIC)

model4 = coef(regfit.bwd,4)
```

```{r}
#problem 2d

```

```{r}
#problem 2e
model1  = lm(crim~ zn + nox + dis + rad + ptratio + black + lstat + medv, data=Boston)
model2  = lm(crim~ zn + indus + nox + dis + rad + ptratio + black + lstat + medv, data=Boston)
model3  = lm(crim~ zn + indus + nox + rm + dis + rad + ptratio + black + lstat + medv, data=Boston)
model4 = lm(crim~ zn + indus + nox + rm + dis + rad + tax+ ptratio + black + lstat + medv, data=Boston)

sum((model1$residuals/(1-lm.influence(model1)$hat))^2)
sum((model2$residuals/(1-lm.influence(model2)$hat))^2)
sum((model3$residuals/(1-lm.influence(model3)$hat))^2)
sum((model4$residuals/(1-lm.influence(model4)$hat))^2)

coef(regfit, 9)
```


